/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ohlcv/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OHLCV candlestick data */
        get: operations["getOhlcv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get technical analysis for a symbol */
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{symbol}/chart-markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get chart annotation markers for viewport */
        get: operations["getChartMarkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{symbol}/chart-overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projection path, EMA, levels and trade setup for chart */
        get: operations["getChartOverlays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sentiment/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get social sentiment for a symbol */
        get: operations["getSentiment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get news for a symbol */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get backtest results for a symbol and strategy */
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/{symbol}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a backtest refresh (quick or full grid) */
        post: operations["refreshBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{symbol}/patterns/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all patterns with active/recent/inactive status */
        get: operations["getPatternsAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{symbol}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger analysis data refresh */
        post: operations["refreshAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/symbols/{symbol}/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cold-start orchestrator — fetch data + quick backtest */
        post: operations["initSymbol"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status and progress */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ranking of crypto assets by clarity score */
        get: operations["getRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get market context (correlations; events when configured) */
        get: operations["getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated dashboard data for a symbol */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Timeframe: "1h" | "4h" | "1D" | "1W";
        /**
         * @default 5y
         * @enum {string}
         */
        HistoryDepth: "2y" | "5y" | "max";
        /** @enum {string} */
        TrendDirection: "bullish" | "bearish" | "neutral";
        /** @enum {string} */
        PatternDirection: "bull" | "bear" | "neutral";
        /** @enum {string} */
        PatternCategory: "candles" | "chart_patterns" | "trend" | "structure" | "indicators" | "levels";
        /** @enum {string} */
        SentimentTone: "positive" | "negative" | "neutral" | "mixed";
        OhlcvCandle: {
            /** @description Unix timestamp in seconds */
            time: number;
            open: number;
            high: number;
            low: number;
            close: number;
            volume: number;
        };
        OhlcvResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            candles: components["schemas"]["OhlcvCandle"][];
        };
        PatternItem: {
            id: string;
            name: string;
            category: components["schemas"]["PatternCategory"];
            direction: components["schemas"]["PatternDirection"];
            bar_time: number;
            confidence: number;
            active: boolean;
            description?: string;
            tf?: components["schemas"]["Timeframe"];
            /** @default false */
            highlight: boolean;
        };
        IndicatorItem: {
            name: string;
            value: number;
            signal: components["schemas"]["TrendDirection"];
            /** @enum {string} */
            zone?: "overbought" | "oversold" | "neutral";
            description?: string;
        };
        Level: {
            price: number;
            /** @enum {string} */
            type: "support" | "resistance";
            strength: number;
        };
        TradeSetup: {
            entry?: number;
            stop_loss?: number;
            take_profit?: number;
            risk_reward?: number;
            direction?: components["schemas"]["TrendDirection"];
        };
        PatternGroup: {
            category: components["schemas"]["PatternCategory"];
            count: number;
            items: components["schemas"]["PatternItem"][];
        };
        AnalysisSummary: {
            trend: components["schemas"]["TrendDirection"];
            trend_strength?: number;
            confluence_score: number;
            highlights: components["schemas"]["PatternItem"][];
            trade_setup?: components["schemas"]["TradeSetup"];
            timeframe_analysis?: {
                [key: string]: {
                    trend?: components["schemas"]["TrendDirection"];
                    strength?: number;
                };
            };
        };
        AnalysisResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            /** Format: date-time */
            updated_at: string;
            summary: components["schemas"]["AnalysisSummary"];
            groups: components["schemas"]["PatternGroup"][];
            indicators: components["schemas"]["IndicatorItem"][];
            levels: components["schemas"]["Level"][];
            pagination?: {
                total?: number;
                page?: number;
                page_size?: number;
            };
        };
        /**
         * @default active_recent
         * @enum {string}
         */
        ChartPatternStatusFilter: "highlight" | "active" | "recent" | "active_recent" | "all";
        /**
         * @default all
         * @enum {string}
         */
        ChartPatternDirectionFilter: "all" | "bull" | "bear";
        ChartMarker: {
            time: number;
            /** @enum {string} */
            position: "aboveBar" | "belowBar" | "inBar";
            /** @enum {string} */
            shape: "arrowUp" | "arrowDown" | "circle" | "square";
            color: string;
            text: string;
            pattern_id?: string;
        };
        ChartProjectionPoint: {
            time: number;
            value: number;
        };
        ChartProjection: {
            direction: components["schemas"]["TrendDirection"];
            target_price: number;
            bars: number;
            path: components["schemas"]["ChartProjectionPoint"][];
            candles: components["schemas"]["OhlcvCandle"][];
        };
        EmaSeries: {
            period: number;
            points: components["schemas"]["ChartProjectionPoint"][];
        };
        ChartOverlaysResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            trend: components["schemas"]["TrendDirection"];
            confluence_score: number;
            projection?: components["schemas"]["ChartProjection"] | null;
            ema: components["schemas"]["EmaSeries"][];
            levels: components["schemas"]["Level"][];
            trade_setup?: components["schemas"]["TradeSetup"];
        };
        SentimentDataPoint: {
            /** Format: date-time */
            time: string;
            score: number;
            mentions: number;
        };
        SocialNetwork: {
            name: string;
            score: number;
            mentions: number;
        };
        SentimentResponse: {
            symbol: string;
            score: number;
            tone: components["schemas"]["SentimentTone"];
            mentions_24h: number;
            mentions_7d?: number;
            trend?: components["schemas"]["TrendDirection"];
            networks?: components["schemas"]["SocialNetwork"][];
            history?: components["schemas"]["SentimentDataPoint"][];
            /** Format: date-time */
            updated_at: string;
        };
        NewsItem: {
            id: string;
            title: string;
            source: string;
            /** Format: date-time */
            published_at: string;
            tone: components["schemas"]["SentimentTone"];
            sentiment_score?: number;
            summary?: string;
            url: string;
        };
        NewsResponse: {
            symbol: string;
            items: components["schemas"]["NewsItem"][];
            summary: {
                positive?: number;
                negative?: number;
                neutral?: number;
                overall_tone?: components["schemas"]["SentimentTone"];
            };
            /** Format: date-time */
            updated_at: string;
        };
        EquityPoint: {
            date: string;
            value: number;
        };
        BacktestJobSummary: {
            id?: string;
            kind?: string;
            /** @enum {string} */
            mode?: "quick" | "full";
            /** @enum {string} */
            status?: "pending" | "running" | "done" | "failed";
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            progress_current?: number;
            progress_total?: number;
            progress_message?: string;
            result?: unknown;
        };
        BacktestResponse: {
            symbol: string;
            strategy: string;
            tf: components["schemas"]["Timeframe"];
            /** @enum {string} */
            status: "empty" | "running" | "ready";
            metrics: {
                total_trades: number;
                win_rate: number;
                profit_factor: number;
                max_drawdown: number;
                sharpe: number;
                avg_return?: number;
            };
            equity_curve?: components["schemas"]["EquityPoint"][];
            /** Format: date-time */
            updated_at: string | null;
            note?: string;
            run_summary?: {
                /** Format: date-time */
                last_run_at?: string | null;
                patterns_with_results?: number;
                total_combos_saved?: number;
                /** @enum {string} */
                grid_mode?: "quick" | "full" | null;
                selection_metric?: string;
            };
            selection?: {
                pattern_id: string;
                pattern_name: string;
                pattern_category?: string | null;
                sort_metric?: string;
                /** Format: date-time */
                run_at?: string | null;
                params?: Record<string, unknown>;
            } | null;
            active_job?: components["schemas"]["BacktestJobSummary"] | null;
            last_job?: components["schemas"]["BacktestJobSummary"] | null;
        };
        RankingItem: {
            rank: number;
            symbol: string;
            confluence_score: number;
            trend: components["schemas"]["TrendDirection"];
            active_patterns: number;
            sentiment_score?: number;
            news_tone?: components["schemas"]["SentimentTone"];
            win_rate?: number;
            price?: number;
            price_change_24h?: number;
        };
        RankingResponse: {
            tf: components["schemas"]["Timeframe"];
            items: components["schemas"]["RankingItem"][];
            /** Format: date-time */
            updated_at: string;
        };
        ContextEvent: {
            id: string;
            title: string;
            date: string;
            type: string;
            /** @enum {string} */
            impact: "alto" | "medio" | "bajo";
        };
        CorrelationItem: {
            asset: string;
            correlation: number;
        };
        ContextResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            events: components["schemas"]["ContextEvent"][];
            correlations: components["schemas"]["CorrelationItem"][];
            /** Format: date-time */
            updated_at: string;
        };
        DashboardResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            combined_score: number;
            technical: components["schemas"]["AnalysisSummary"];
            sentiment?: components["schemas"]["SentimentResponse"];
            news?: components["schemas"]["NewsResponse"];
            backtest?: components["schemas"]["BacktestResponse"];
            disclaimer?: string;
            /** Format: date-time */
            updated_at: string;
        };
        PatternAllItem: {
            id: string;
            name: string;
            category: components["schemas"]["PatternCategory"];
            /** @enum {string} */
            status: "active" | "recent" | "inactive";
            direction: number;
            last_occurrence_bars_ago?: number | null;
            occurrences_last_100_bars?: number;
            description?: string;
        };
        PatternsAllResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            total_patterns: number;
            active: number;
            recent: number;
            inactive: number;
            patterns: components["schemas"]["PatternAllItem"][];
        };
        InitResponse: {
            symbol: string;
            tf: components["schemas"]["Timeframe"];
            history: components["schemas"]["HistoryDepth"];
            data_job_id: string;
            backtest_job_id: string;
            status: string;
        };
        JobResponse: {
            id: string;
            kind: string;
            payload?: Record<string, never>;
            /** @enum {string} */
            status: "pending" | "running" | "done" | "failed";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            result?: Record<string, never> | null;
            progress_current?: number;
            progress_total?: number;
            progress_message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOhlcv: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OHLCV data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcvResponse"];
                };
            };
        };
    };
    getAnalysis: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                category?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Technical analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
        };
    };
    getChartMarkers: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                history?: components["schemas"]["HistoryDepth"];
                from?: number;
                to?: number;
                min_confidence?: number;
                pattern_status?: components["schemas"]["ChartPatternStatusFilter"];
                pattern_direction?: components["schemas"]["ChartPatternDirectionFilter"];
                /** @description Comma-separated pattern categories (e.g. candles,trend) or omit for all */
                categories?: string;
                max_markers?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart markers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartMarker"][];
                };
            };
        };
    };
    getChartOverlays: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                history?: components["schemas"]["HistoryDepth"];
                projection_bars?: number;
                min_level_strength?: number;
                max_levels_per_side?: number;
                min_confluence?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart overlay bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOverlaysResponse"];
                };
            };
        };
    };
    getSentiment: {
        parameters: {
            query?: {
                window?: "1h" | "4h" | "24h" | "7d";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sentiment data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResponse"];
                };
            };
        };
    };
    getNews: {
        parameters: {
            query?: {
                limit?: number;
                sentiment?: "positive" | "negative" | "neutral" | "all";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description News items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    getBacktest: {
        parameters: {
            query?: {
                strategy?: string;
                tf?: components["schemas"]["Timeframe"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backtest results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
        };
    };
    refreshBacktest: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                mode?: "quick" | "full";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    getPatternsAll: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                history?: components["schemas"]["HistoryDepth"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All patterns with status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternsAllResponse"];
                };
            };
        };
    };
    refreshAnalysis: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    initSymbol: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                history?: components["schemas"]["HistoryDepth"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs queued for initialization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of recent jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
        };
    };
    getRanking: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
                symbols?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
        };
    };
    getContext: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Context data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: {
                tf?: components["schemas"]["Timeframe"];
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
}
